### ISSUE TITLE
Improve the algorithm to search for views in the Story Map Engine

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#1013]
**Edited for clarity**:

#### New content

Summary:
- Some public views cannot be found when searching for very pertinent terms that are in their titles (even when searching for the whole title) - even in case no other view is found (ex. the view "Marine and terrestrial protected areas" cannot be found at all no matter what we search for, and no other results are given when the entire title is searched).
- Public views that only match one of the searched terms in the abstract are found while views which have all terms in the title are not found
- Some public views can be found when searching for some specific terms while they are not found when searching for other terms in their title (ex. the view "GHS population grid (2020)" is not found when "population" or "population grid" are searched, but it is found when "GHS population" is searched).

Proposed solutions:
- [ ] Sort the results based on:
1. - [ ] Matches found in Title, then keywords, then abstract
2. - [ ] Number of searched terms that are matched
3. - [ ] Matches that are found in the current project
4. - [ ] Matches that are published in projects like Base Data, Home, and the thematic projects handled by GRID (need a solution in db to attribute this flag to some projects)

The last point would be cool to have as it would emphasize our work of collection of relevant layers for environmental topics. 

------------
#### Old content
The story map engine offers a search tool that help finding views that should be added to steps. The results of this research are currently not satisfying as they currently do not list views which should be listed even if only a few results are found unless the searched terms are changed.

For instance, the view "GHS population grid (2020)" is not found when "population" or "population grid" are searched, but it is found when "GHS population" is searched.

The criteria used by the tool could be improved by giving **higher priority** to results that match the **highest number of words searched** and to results that matches the searched words **in the title** rather than in the abstract. Pertinence should lower for partial match results (some words found, not all) and for matches that are found in the abstract only.

**Comment by fxi** [comment]
Search is now fully handled by tom-select, replacing the previous approach that was based on a regex pre-filter . The cache is invalidated when the language, project, or user changes, solving case when title was not found because of a language change, before the TTL.

Keep in mind : 
- Story views search must support both user views and the public catalogue. It's client-side, heavy, and not yet optimized, but maintains a cache + tom-select internal search engine.
- MapX Catalogue search is more efficient but only works with public views.
- Keywords don't exist in view space, only sources. The catalogue uses a complex query to associate source tags/metadata to views, unlike simpler story map view lists.

From your examples, tested locally  in 1.13.11-beta.1 : 
- GHS Population Grid (2020): Not found in story views (expected); found in catalogue via fuzzy matching.
- Population Distribution (GHSL) 2020: Found in both story views and catalogue.

Proposed Improvement: 
- Building an hybrid search engine: use fuzzy search in Postgres ( like we do for Gemet ) for personal views and our current search engine for public views. Open a new issue for this if required. Everything exists already, but must be connected + websocket endpoint created.

**Comment by thomaspiller** [comment]
Thanks. After some testing, I find that the new search system is much more efficient and returns the expected views with much more reliability.

**Comment by antobenve** [comment]
Thanks, I also find the results more pertinent.
