### ISSUE TITLE
null values in pop-up/dashboards

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#903]
I just noticed that the management of nulls in the pop-up as well as in dashboards (when an item is clicked in the map to get data) has changed. Indeed, secondary attributes with a null value are no longer displayed/returned, whereas it seems to me that was the case before.

This change may have been made a long time ago and it took me this long to notice.

Is this something to fix or is this normal behavior?

**Example (single view):**
- Feature without nulls:
  <img src="https://user-images.githubusercontent.com/19908801/232723569-734959b9-1ee7-41b6-ad17-8b5e33b9ba3d.png" width="500">
- Feature with nulls:
  <img src="https://user-images.githubusercontent.com/19908801/232723475-50a594db-4469-428f-af16-970da1000763.png" width="500">

**Comment by antobenve** [comment]
This could explain why the code of the widget of a specific view that relied on the data clicked (that also contained Nulls) was not working properly and needed to be refactored. We probably didn't realize the issue before because every attribute was extracted at clicks even when its value was NULL.

**Comment by thomaspiller** [comment]
Secondary attributes with a `NULL` value are displayed as `$NULL` in the pop-up.
