### ISSUE TITLE
Add base map that uses the mapbox-streets-v12 style (partly edited)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#915]
### Objective
 Integrate the [mapbox streets-v12 base map](https://www.mapbox.com/maps/streets) as an optional base map that the users can activate with one click.

#### Proposed interface solution
The satellite button in the right-hand side panel switches from 1) the current base map to 2) the satellite imagery and then 3) to the mapbox streets-v12 base map.

#### Careful
The default style of the mapbox streets-v12 base map should be edited in order NOT to show the following entities, which are instead to be displayed using our tileset:
- Country borders
- Subnational borders
- Country names
- Cities and villages names

**Comment by fxi** [comment]
Implementing this might be challenging due to a few key reasons. Firstly, we are using a custom theme managed by a theme manager specifically built for our purposes, and this is unfortunately incompatible with Mapbox-Street. In addition, Mapbox does not utilize the same set of fonts/glyphs and sprites that we use, at least, partially.

Furthermore, you've identified issues with non-UN-standard names, borders, and polygons, which significantly hamper the implementation of this particular style.

This seems to be a case of an 'X-Y problem': you have a problem X and you're attempting to solve Y, when in fact, the root of the issue lies upstream. Could you please elaborate on the original problem? This will likely help us in identifying a more suitable solution or compromise.

**Comment by thomaspiller** [comment]
It is possible to get close to the mapbox streets-v12 base map with the theme editor in MapX. The Vegetation layer might be missing but is easy to add.

**Comment by antobenve** [comment]
The request is based on Pascal's wishes. He would like to have the possibility to display the base map from OpenStreetMap Carto (which I believe it is served by Mapbox streets) because it shows elements that are useful for the identification of targets such as forested areas vs grasses vs bare land and buildings.

He proposed we create a view with such tiles. We propose a switch on map to change base map from the current base map, to the OSM base map, to the satellite imagery because we think the solution is cleaner and easier to access and use by users (same reason why the satellite view was moved to the switch).

**Comment by antobenve** [comment]
Any solution is good as long as it is compatible with the theme manager and the result is similar to the one requested by Pascal.

**Comment by fxi** [comment]
<img width="1004" alt="image" src="https://github.com/unep-grid/mapx/assets/1196833/1c8f8471-66e3-4d07-9cac-85689a9f9a47">

**Comment by thomaspiller** [comment]
Thanks. The theme you developed comes out well and I think it is close to what was requested. To be validated with Pascal ASAP.

**Comment by thomaspiller** [comment]
After consultation with our partners, the fact that the water light/dark theme is no longer available in MapX is problematic.
Following an internal discussion, this theme should be reintegrated into MapX as currently available in production.
3 different themes will then be available: monochrome, water & color with 2 modes for each dark/light.
