### ISSUE TITLE
New URL option to set panels visibility

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#925]
Add an option in the URL to define how each panel should be rendered in MapX.
Three modes would be available:
- `visible` (default): the panel button is displayed and the panel is closed on loading
- `open`: the panel button is displayed and the panel is open on loading
- `hidden`: the panel button is not displayed at all

Basic examples: `panelNotification=hidden` or `panelLegend=open`.
It might also be relevant to add a method to the `SDK`  to set/update this parameter dynamically (TBC).

**Comment by fxi** [comment]
This request might conflict with two other functions:

- `closePanels`: This URL parameter controls the opening and closing of the main and tools panels.
- `setImmersiveMode`: This SDK method can show/hide or open/close panels.
- `panel_disable`: Represents story map settings. It's an array that lists panels to disable. They get re-activated after the story is closed.

Before implementing any changes, it's essential we discuss the approach. Ideally, we should have a panel manager, where all the entry points (SDK, story, URL, helper) interact with it. This would give a clear state. Currently, we're just dealing with an array of instances and iterating over them.

For instance, if the panel "notif_center" is hidden using `panelNotification=hidden` in the URL but is also set to `hidden` for a story map, it will appear after the story map concludes – which isn't the expected behavior. I've yet to explore other potential issues; this is just my initial observation.

**Comment by thomaspiller** [comment]
@fxi  Thanks for the feedback. The panel manager you proposed meets the needs of our partners and will bring a lot of flexibility, especially when using the SDK. We can move forward with this option.

**Comment by fxi** [comment]
- [x] PanelManager implementation : https://github.com/unep-grid/mapx/blob/staging/app/src/js/button_panel/manager.js
- [x]  Updated url params in the wiki : https://github.com/unep-grid/mapx/wiki/URL-parameters
- [x]  Added SDK resolvers + documentation : https://github.com/unep-grid/mapx/tree/staging/app/src/js/sdk#MapxResolversPanels 
- [ ]  Added SDK tests ( waiting for feedback @thomaspiller, @trepmag   )

-> will be available in the next release

**Comment by thomaspiller** [comment]
For me, the implementation of the panel manager covers our needs well. I don't see any other methods to add. Can't wait to get my hands on it to test. Thanks!
