### ISSUE TITLE
Metadata: missing countries in geographical keywords

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#955]
Some countries are missing in the drop-down list of geographical keywords, e.g. Morocco, Algeria.
By directly editing the JSON, it is possible to add these countries (ISO 3 code) which are then listed in the UI.

**Comment by antobenve** [comment]
I think the issue is slightly different as I can see them in the list and as they were already used in source layers previously.
The problem is that those keywords are only found if the user enters the ISO3CODE, instead of the country name in the current language.
![image](https://github.com/unep-grid/mapx/assets/30286565/7792e354-36c7-4c93-ae35-a94efead9308)
