### ISSUE TITLE
Add button (easy to find) to MapX Wiki

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#959]
An entry point to the Home of the MapX wiki should be added in the interface. The button should be easy to discover.

Summary of the proposed options by priority:

1.  A "?" (tooltip: "Help") button in the navigation panel (right panel) at the place of the "Spotlight vector features" button which could be removed from MapX.
2. A "Help" button in the left panel (could be next to project title or in some other easy to spot places)

**Comment by thomaspiller** [comment]
One option could be to add this new button in the right toolbar.

**Comment by PierreLacroix** [comment]
One possibility could be to remove the Spotlight Vector Features button in the right toolbar, to include this new button (link to MapX Wiki) and to reorder some buttons in the toolbar

**Comment by fxi** [comment]
I think that the Spotlight Vector Features button is an essential tool for users to efficiently identify isolated or overlapping features within the current zoom level. It proves particularly valuable in instances where the map's styling may not be optimal, such as when features are rendered invisible due to insufficient contrast or suboptimal size choices. It should remain in the controls panel. 

I've added a link to the wiki in the toolbox. 
<img width="254" alt="image" src="https://github.com/unep-grid/mapx/assets/1196833/693041a0-37f9-4763-b952-8eacdc204b6b">
