### ISSUE TITLE
Column Renaming via Table Editor Causes Locking and Service Failures 

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#967]
Renaming a column from the table editor has detrimental consequences on MapX which becomes non-responsive due to locked connections in the database. An investigation is underway to understand the cause of the problem. As this is a critical issue, a patch will be pushed as quickly as possible to resolve this situation.

**Comment by fxi** [comment]
The issue should be resolved as of commit 8645172d (version `1.12.6-patch.1`). In the rename handler ( table editor), there was an update on `mx_sources` that triggered the `mx_sources_meta_keywords` materialized view. This operation, being part of an encompassing transaction, failed to execute properly. Consequently, the trigger did not succeed and resulted in locking the involved tables indefinitely. This occurred without generating any logs or errors, thereby failing silently. Although all related service health checks triggered their restart mechanisms, they were ineffective due to the persistence of the issue within the database's state.

Here's what was changed to address the problem:

- The inner transaction logic within the `mx_source` timestamp helper has been removed, eliminating redundant logic.
- This helper now utilizes the same database client and transaction context as the initiating process, effectively resolving the issue.
- Optimization has been achieved by performing the helper's action once per batch rather than after each individual update item, enhancing performance.

If any related problems persist, please complete this issue.
