### ISSUE TITLE
Delete a project: Admin should be informed about views that are shared towards other projects before clicking Delete.

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#994]
When deleting a project, the admin is asked to review all potential changes provoked by this action through a list of views and sources that will be deleted. 

Currently, this list doesn't include the list of projects where some of the views are shared to.

This information could be added in an additional column of 

**Table of views to delete :**
id | title | shared to projects
-- | -- | --
MX-MYIVL-5NFGF-HS6P9 | drawn | 
MX-2NE41-ANS4D-EQO0Z | Global old | TEST Antonio, Base, GEMS Ocean ...
MX-KYP8F-UAHJO-BNKT7 | hippies | 

The list of projects being potentially very large should be expandable in some way (mouse hover? or click for an additional module to open?)

**Comment by antobenve** [comment]
#287

**Comment by antobenve** [comment]
The panel looks good.
However, a subset of story maps is not taken into account when checking if a view is used in a story map. 
This can be fixed with the following edit of the SQL request in [line 170](https://github.com/unep-grid/mapx/blob/cb2e5cf94fb5eb6149582a78d225c279d9511181/app/src/r/server/tools_project_delete.R#L170):
`story_view::text` -> `story_view ->> 0`

```
story_views_clean as (
    SELECT
      story_id,
	  CASE
	  WHEN
	  jsonb_typeof(story_view) = 'object' THEN story_view ->> 'view'
	  ELSE
	  --story_view::text 
          story_view ->> 0
	  END as story_view
    FROM
      story_views
  )
```

**Comment by fxi** [comment]
Ok, this took me a while. There was no reproducible example, so I was guessing based on my local values, where I had no issues. Once I started using real data values, things became clearer.

Since the introduction of the new views selection tools, we now store views as `["a","b","c"]` instead of `[{"view":"a"},{"view":"b"},{"view":"c"}]`. In the first iteration of the tool, we stored the full view as `[{"view":<full view>}]` to create something self-contained and avoid breaking changes, essentially "freezing" the view version. However, since users were storing vast amounts of data in these views (with the limit being multi-MB), it quickly became unmanageable. 

To address this, we introduced the second method: storing views as `{"view":"<id>"}` to avoid breaking schema rules entirely. Eventually, we moved to storing them as `["a","b","c"]`, which aligns with the classic array editor and simplifies the process. However, this change introduced an inconsistency. The normal array expansion to text is done with `jsonb_array_elements_text`. To handle old objects, we needed a cleanup step, so we used `jsonb_array_elements` to expand the `jsonb` values, followed by casting them to strings. However, casting using PostgreSQL's base function retains the JSON quotes.

Here’s a minimal working example:

```sql
WITH
  a AS (
    SELECT
      jsonb_array_elements('["a","b"]'::jsonb) AS ids
  )
SELECT
  ids::text AS quoted,
  CAST(ids AS text) AS quoted_cast,
  ids ->> 0 AS ok_but_why,
  ids #>> '{}' AS ok_doc
FROM
  a;
```

Resulting in:

| quoted | quoted_cast | ok_but_why | ok_doc |
|--------|-------------|------------|--------|
| "a"    | "a"         | a          | a      |
| "b"    | "b"         | b          | b      |

The earlier method, `->> 0`, worked, but it's unclear why, as it's not documented (it could be a short-lived hack, as the [source code](https://github.com/postgres/postgres/blob/04bec894a04cb0d32533f1522ab81b7016141ff1/src/backend/utils/adt/jsonfuncs.c#L936) indicates that the `jsonb` must be an array and not a string). 

The second method, using `#>> '{}'`, seems more correct, as it explicitly selects the path we need and isn't limited to arrays.
